name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.202'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    # - name: Test with dotnet
    #   run: dotnet test ./lori.backend.sln --configuration Release